name: Update Subscription

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download Subscription
        run: |
          curl -L \
          -A "Mozilla/5.0" \
          "https://kafa.louisestallser.workers.dev/6766942c-8b88-4bab-9512-ee30fc1db347/sub" \
          -o Configs.txt

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add Configs.txt

          git diff --quiet && git diff --staged --quiet || git commit -m "Update configs"

          git push
